env: dev
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.cj.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloud_shell?characterEncoding=utf-8&useSSL=false
    username: root
